channels:
  - defaults
  - conda-forge
dependencies:
  - notebook
  - cookiecutter
  - black
  - jupyterlab
  - lxml
  - matplotlib
  - odfpy
  - poppler
  - python-dotenv
  - seaborn
  - plotly
  - nbqa
  - pandas
  - python-kaleido
  - chart-studio
  - ipywidgets
  - plotly::plotly-geo